# Generated by Django 3.0.1 on 2021-08-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='completed',
            field=models.DateField(),
        ),
    ]
