# Generated by Django 3.0.1 on 2021-08-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_auto_20210815_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='category_home'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='completed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
