# Generated by Django 3.0.1 on 2021-08-16 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_auto_20210815_0354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialty',
            options={'verbose_name': 'Especialidad', 'verbose_name_plural': 'Especialidades'},
        ),
    ]
