# Generated by Django 3.0.1 on 2021-08-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0006_auto_20210830_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='content',
            field=models.TextField(default='Servicio', help_text='Texto que explicará el servicio en cuestión', max_length=500),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(help_text='Texto que aparecerá en la sección inicial', max_length=100),
        ),
        migrations.AlterField(
            model_name='services',
            name='completed',
            field=models.DateField(blank=True, help_text='Fecha de completación de la obra', null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='content',
            field=models.CharField(help_text='Descripción de la obra', max_length=50, null=True),
        ),
    ]
