# Generated by Django 3.0.1 on 2021-09-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0007_auto_20210830_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='content',
            field=models.CharField(blank=True, help_text='Descripción de la obra', max_length=50, null=True),
        ),
    ]
