# Generated by Django 3.0.1 on 2021-09-03 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0008_auto_20210903_0108'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
    ]
