# Generated by Django 3.0.1 on 2021-09-04 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0012_auto_20210904_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
