# Generated by Django 3.0.1 on 2021-09-03 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home_app', '0009_delete_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('completed', models.DateField(blank=True, help_text='Fecha de completación de la obra', null=True)),
                ('content', models.CharField(blank=True, help_text='Descripción de la obra', max_length=50, null=True)),
                ('image', models.ImageField(upload_to='services_home')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_app.Category')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
    ]
