# Generated by Django 5.1 on 2024-08-27 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('service_name',), 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, help_text='URL que tendrá la categoría', null=True, unique=True)),
                ('description', models.CharField(blank=True, help_text='Descripción de la obra', max_length=255, null=True)),
                ('image', models.ImageField(upload_to='project_projects')),
                ('thumbnail', models.ImageField(upload_to='project_projects')),
                ('completedAt', models.DateField(help_text='Fecha en la que se completo la obra')),
                ('service_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='services_app.service')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ('title',),
            },
        ),
    ]
