# Generated by Django 5.1 on 2024-08-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0002_alter_service_options_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='project_projects'),
        ),
    ]
